---
# defaults for cpswtng-cloud-cli

project: cpswtngdefaultproject
projects_dir: ./projects

# currently supported platforms: [ "openstack" ]
platform: openstack

network:
  cidr: auto # 10.4.100.0/24
  cidr_template: 10.X.100.0/24
  ext_net_name: 'ext-net'

# ### HOSTS related information ###

vm_management:
  default_image_name: 'Ubuntu 14.04.2_20150505'
  default_vm_flavor: 'm1.medium'
  hosts_startup_timeout: 600
  terminate_vm_poll: 2

# "hosts" key indicates the array of host descriptors
hosts:
  - name: bastion_host
    vm_flavor: m1.small
    count: 1 # optional, default value is 1
    image_name: 'Ubuntu 14.04.2_20150505'
    cloud_vars:
      - index: 0
        assignPublicIP: true
    ansible_settings:
      - ansible_group: bastion
        item_vars:
          - ansible_host: public_ip # public_ip | private_ip
          - hostname: host_name

  - name: mesos_master
    vm_flavor: m1.large
    count: 1
    cloud_vars:
      - index: 0
        assignPublicIP: true
    ansible_settings:
      - ansible_group: mesos_master
        group_vars:
          - index: 0
            useAsMarathonHost: true
        item_vars:
          - ansible_host: private_ip
          - hostname: host_name
      - ansible_group: zookeeper
        group_vars:
          - index: 0
            zoo_id: 1

  - name: mesos_agent
    vm_flavor: m1.large
    count: 2
    cloud_vars:
      - index: 0
        assignPublicIP: false
    ansible_settings:
      - ansible_group: mesos_agent
        group_vars:
          - index: 0
            useAsMarathonHost: true
        item_vars:
          - ansible_host: private_ip
          - hostname: host_name

ansible:
  ansible_dir: ~/projects/c2wt/repos/cpswtng-ansible/
  playbook: playbooks/setup_mesos_cluster.yml
  inventory_template: inventory/cluster_template.j2