---
# defaults for cpswtng-cloud-cli

project: cpswtngdefaultproject
projects_dir: ./projects

# currently supported platforms: [ "openstack" ]
platform: openstack_driver
platform_settings: ./config/openstack.yml

network_cidr: auto # 10.4.100.0/24
network_cidr_template: 10.X.100.0/24
ext_net_name: 'ext-net'

# "hosts" key indicates the array of host descriptors
hosts:
  - name: bastion_host
    type: bastion
    count: 1 # optional, default value is 1
    first:
      assignPublicIP: true
    ansible_vars:
      - type: bastion

  - name: mesos_master
    type: mesos_master
    count: 3
    first:
      assignPublicIP: true
    ansible_vars:
        - type: mesos_master
        - useAsMarathonHost: true
          multiplicity: unique

  - name: mesos_agent
    type: mesos_agent
    count: 2
    ansible_vars:
        - type: mesos_agent