---
# defaults for lusheeta-cli

# project settings
project: lusheetaproject # cli argument overwrites this
projects_dir: ./projects

# currently supported platforms: [ "openstack" ]
platform: openstack

# network settings
network:
  cidr: auto # or 10.4.100.0/24
  cidr_template: 10.X.100.0/24
  ext_net_name: 'ext-net'

# VMs
vm_management:
  default_image_name: 'Ubuntu 14.04.2_20150505'
  default_vm_flavor: 'm1.medium'
  hosts_startup_timeout: 600
  terminate_vm_poll: 2

# host settings
hosts:
  - name: bastion_host

    # overrides default_vm_flavor
    vm_flavor: m1.small

    # optional, default value is 1
    count: 1

    # overrides default_image_name
    image_name: 'Ubuntu 14.04.2_20150505'
    cloud_vars:
      - index: 0
        assignPublicIP: true
    ansible_settings:
      - ansible_group: bastion
        item_vars:
          - ansible_host: public_ip # public_ip | private_ip
          - hostname: host_name

  - name: mesos_master
    vm_flavor: m1.large
    count: 1
    cloud_vars:
      - index: 0
        assignPublicIP: true
    ansible_settings:
      - ansible_group: mesos_master
        group_vars:
          - index: 0
            useAsMarathonHost: true
        item_vars:
          - ansible_host: private_ip
          - hostname: host_name
      - ansible_group: zookeeper
        group_vars:
          - index: 0
            zoo_id: 1

  - name: mesos_agent
    vm_flavor: m1.large
    count: 2
    cloud_vars:
      - index: 0
        assignPublicIP: false
    ansible_settings:
      - ansible_group: mesos_agent
        group_vars:
          - index: 0
            useAsMarathonHost: true
        item_vars:
          - ansible_host: private_ip
          - hostname: host_name

# ansible settings
ansible:
  ansible_dir: ./example/ansible
  playbook: playbooks/setup_mesos_cluster.yml
  templates_path: ./example/templates
  inventory_template: ansible_inventory.j2 # optional
  ssh_config_template: ssh.config.j2 # optional
  ansible_cfg_template: ansible.cfg.j2 # optional
