---
# Supported platforms
#
# platform:
#  module_name: <the python filename you implemented>
#  class_name: <the name of the class in the implementation>

openstack:
  module_name: openstack_driver
  class_name: OpenStackDriver
  settings_file: ./config/openstack.yml